### ISSUE TITLE
Noob having a hard time

### ISSUE THREAD

**Issue by hsavit1** [nryoung/algorithms#118]
Just trying to run the tests

when i run python test_random.py in the console I get this output

➜  tests  python test_random.py
Traceback (most recent call last):
  File "test_random.py", line 3, in <module>
    from algorithms.random import mersenne_twister
ImportError: No module named random

**Comment by nryoung** [comment]
Hey there. This is to due to the fact that `algorithms` isn't in your `PYTHONPATH` and the `tests` and `algorithms` packages are at the same directory level.

But, you ask yourself, how can you run individual tests then? Well, have no fear, from the root of the repo simply run:

```shell
$ python -m unittest tests.test_random
```
Since we are executing this from the root repo it can see both the `algorithms` and `tests` packages and knows to invoke the `unititest` module.

In reality, if you are making modifications you will want to install the dependencies from `requirements.txt` and run the tests via the nifty test runner:

```shell
$ ./run_tests.py
```

Let me know if you have further questions. Closing this one out, Cheers!

**Comment by hsavit1** [comment]
Hey thanks for the timely response! 

When I run

➜  algorithms-master  python -m unittest tests.test_searching
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK

Is this the expected result? I feel like it's not fully executing the test?

**Comment by nryoung** [comment]
Hey @hsavit1,

I am not really sure what you mean? Looking at the `tests.tests_searching` there are 5 tests in that module and the output you included above shows five tests being run.

If you could elaborate on what result you are expecting?

**Comment by hsavit1** [comment]
One thing I haven't done is I haven't install the dependencies in requirements.txt. How can I do that? Should I install each with PIP?

**Comment by nryoung** [comment]
If you want install the requirements then you can simply do:
```shell
$ pip install -r requirements.txt
```
