### ISSUE TITLE
Bug in BFS implementation

### ISSUE THREAD

**Issue by erezsh** [nryoung/algorithms#157]
https://github.com/nryoung/algorithms/blob/master/algorithms/searching/breadth_first_search.py

You are using a list as the queue, and pop(0) is an O(N) operation, which turns your complexity to O(N**2) instead of O(V+E). Use deque or something, this is pretty basic stuff guys.

Also, it's a little close-minded assuming you would only run bfs on a graph. 

Here, use my implementation. It accepts a callback instead of a graph, uses yield which is nicer and lazy (the good kind), and it's correct (afaik):

`
def bfs(initial, expand):

    open_q = collections.deque(list(initial))

    visited = set(open_q)

    while open_q:

        node = open_q.popleft()

        yield node

        for next_node in expand(node):

            if next_node not in visited:

                visited.add(next_node)

                open_q.append(next_node)
`

**Comment by nryoung** [comment]
> You are using a list as the queue, and pop(0) is an O(N) operation, which turns your complexity to O(N**2) instead of O(V+E). Use deque or something, this is pretty basic stuff guys.

I am pretty sure the complexity could for `pop(0)` is generally `O(log n)`, BUT this is highly implementation dependent. That is why `O(V+E)` is a pretty safe bet. Also, just because this may seem basic to you, does not basic for other people trying to learn these concepts.

> Also, it's a little close-minded assuming you would only run bfs on a graph.

I do not really understand what is close minded here.

> Here, use my implementation. It accepts a callback instead of a graph, uses yield which is nicer and lazy (the good kind), and it's correct (afaik):

Definitely an interesting approach. I would highly encourage you to create a PR with corresponding tests to ensure that your implementation does indeed work correctly.

I am going to close this out, but please consider opening a PR with your fixes. Thanks.
