### ISSUE TITLE
An active fork of this repo

### ISSUE THREAD

**Issue by JoaoGFarias** [nryoung/algorithms#74]
Fellas,

I've send several e-mails to @nryoung asking him about this repo; if the
pull requests will ever be merged.
No answer came.

I've decide to [fork](https://github.com/JoaoGFarias/algorithms) this repo and manage the pull requests.
I see this project as a great showcase of Python for new programmers,
therefore, see this inactive is a shame. 
If you guys want your code incorporated, you can send me pull requests
[here](https://github.com/JoaoGFarias/algorithms).

As soon as @nryoung appears again, I will send a pull request
with the changes to this repo and close the fork; if it ever happen.

**Comment by nryoung** [comment]
Hey @JoaoGFarias ,

I have had a lot going on in my personal life recently.

I have been doing some thinking recently, and I have decided that I no longer want to spend a lot of time maintaining this repo. However, I certainly do not want this repo to die, because I do agree with you that this repo can be a great learning resource for new programmers.

That being said, I think I would like to add a few maintainters to this project to allow it to grow and allow the contributions to be merged in a timely manner. I would, however, like to remain a maintainer as well, and pop in every once in a while.

Would you want to be a maintainer?

Let me know and hopefully we can get this project back up and running.

**Comment by JoaoGFarias** [comment]
Surely @nryoung, this would be easiest and best solution. 
I and the other maintainers can try filter the discussions and, together with you, make decisions regarding any modifications on the repo.

Do you have other contributors in mind to be on this role?

**Comment by nryoung** [comment]
I actually don't have any other contributers in mind at the moment. I will get you maintainer rights to the repo by tonight.
